# step 1: build stage
FROM node:14.16.0-alpine3.13 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV REACT_APP_API_URL=http://159.89.37.140:3001/api
RUN npm run build


# step 2: production stage
FROM nginx:1.12-alpine AS production-stage
#RUN addgroup app && adduser -S -G app app
#USER app
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ] 